Repository hyperledger/sawtooth-next-directory, pull requests merged in 2018-09, with the labels that each got.

#41 Added Agnes' issue templates for NEXT
  .github/ISSUE_TEMPLATE/-epic--epic-template.md
  .github/ISSUE_TEMPLATE/-user-story--user-story-template.md
Labels: enhancement

#51 Added Agnes' task issue template
  .github/ISSUE_TEMPLATE/-task--task-template.md
Labels: enhancement

#52 Added username to integration tests
  integration_tests/blockchain/blockchain_integration_test.py
Labels: bug

#120 S2+ Adds test data loader
  README.md
  bin/populate_test_data.py
Labels: Infra

#121 S2+ Bugfix/persistent data
  .dockerignore
  .gitignore
  README.md
  bin/start
  bin/stop
  docker-compose-dev.yaml
  docker-compose.yaml
  docker-dev.yaml
  docker-persist.yaml
Labels: bug
