Repository hyperledger/sawtooth-next-directory, pull requests merged in 2018-11, with the labels that each got.

#433 Manually change package-lock.json 'merge' dependency
  client/package-lock.json
Labels: security

#450 Reverted logo path, updated gitattributes
  .gitattributes
  README.md
Labels: blocking

#451 Replaces logos with valid binaries
  docs/_static/logo-full.png
  docs/_static/logo-thumb.png
  logo.png
Labels: bug

#449 Add ability to fetch proposal
  client/src/components/layouts/ApprovalCard.js
  client/src/components/layouts/MemberList.js
  client/src/containers/app/App.js
  client/src/containers/requester/Requests.js
  client/src/images/next-logo-landing.gif
  client/src/redux/RequesterRedux.js
  client/src/redux/UserRedux.js
  client/src/sagas/RequesterSaga.js
  client/src/sagas/index.js
  client/src/services/Api.js
Labels: NEXT UI

#455 Improve requests / recommended screens
  client/package-lock.json
  client/package.json
  client/src/components/layouts/ApprovalCard.css
  client/src/components/layouts/ApprovalCard.js
  client/src/components/layouts/Header.css
  client/src/components/layouts/Header.js
  client/src/components/layouts/MemberList.js
  client/src/components/layouts/TrackHeader.css
  client/src/components/nav/RequesterNav.js
  client/src/containers/app/App.js
  client/src/containers/requester/Recommended.css
  client/src/containers/requester/Recommended.js
  client/src/containers/requester/Requests.css
  client/src/containers/requester/Requests.js
  client/src/images/next-logo-landing.gif
  client/src/redux/UserRedux.js
  client/src/sagas/UserSaga.js
  client/src/sagas/index.js
  client/src/services/Api.js
Labels: NEXT UI

#504 Adds docs build status badge to README
  README.md
Labels: documentation

#521 Add favicons for all media
  client/public/android-chrome-192x192.png
  client/public/android-chrome-384x384.png
  client/public/apple-touch-icon.png
  client/public/browserconfig.xml
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/mstile-150x150.png
  client/public/safari-pinned-tab.svg
Labels: NEXT UI

#518 Codebase simplification
  rbac/common/base/base_address.py
  rbac/common/base/base_message.py
  rbac/common/crypto/fernet.py
  rbac/common/crypto/keys.py
  rbac/common/crypto/secrets.py
  rbac/common/sawtooth/batcher.py
  rbac/common/sawtooth/client_sync.py
  rbac/server/api/auth.py
  rbac/server/api/users.py
  rbac/server/api/utils.py
  tests/rbac/common/crypto/key_assertions.py
  tests/rbac/common/crypto/test_keys.py
  tests/rbac/common/role/create_role_test.py
  tests/rbac/common/sawtooth/test_batcher.py
  tests/rbac/common/task/create_task_test.py
  tests/rbac/common/user/create_user_bad_test.py
Labels: NEXT Directory, coding standards, technical debt

#540 Individuals screen selection functionality +
  client/src/components/chat/Chat.css
  client/src/components/chat/Chat.js
  client/src/components/forms/LoginForm.js
  client/src/components/forms/SignupForm.js
  client/src/components/layouts/ApprovalCard.js
  client/src/components/layouts/proposals/PeopleList.css
  client/src/components/layouts/proposals/PeopleList.js
  client/src/components/nav/RequesterNav.js
  client/src/containers/app/App.js
  client/src/containers/app/AppHelper.js
  client/src/containers/approver/ApproverHome.css
  client/src/containers/approver/Individuals.css
  client/src/containers/approver/Individuals.js
  client/src/containers/login/Login.js
  client/src/containers/requester/Recommended.css
  client/src/containers/requester/Recommended.js
  client/src/containers/requester/Recommended.test.js
  client/src/containers/requester/Requests.css
  client/src/containers/requester/Requests.js
  client/src/containers/requester/Requests.test.js
  client/src/index.css
  client/src/mock_data/conversation_action.1.json
  client/src/redux/RequesterRedux.js
  client/src/redux/UserRedux.js
  client/src/sagas/RequesterSaga.js
  client/src/sagas/RequesterSaga.test.js
  client/src/sagas/UserSaga.js
  client/src/sagas/index.js
  client/src/services/Utils.js
Labels: NEXT UI

#594 Update batch select
  client/src/components/chat/Chat.css
  client/src/components/chat/Chat.js
  client/src/components/layouts/TrackHeader.css
  client/src/components/layouts/TrackHeader.js
  client/src/components/layouts/proposals/PeopleList.js
  client/src/components/nav/ApproverNav.js
  client/src/components/nav/IndividualsNav.css
  client/src/components/nav/IndividualsNav.js
  client/src/components/nav/InvidivualsNav.test.js
  client/src/containers/approver/Batch.js
  client/src/containers/approver/Batch.test.js
  client/src/containers/approver/Frequent.css
  client/src/containers/approver/Frequent.js
  client/src/containers/approver/Individuals.js
  client/src/containers/approver/IndividualsHelper.js
  client/src/containers/approver/People.js
  client/src/containers/approver/Roles.css
  client/src/containers/approver/Roles.js
  client/src/containers/approver/Roles.test.js
  client/src/containers/requester/Packs.js
  client/src/containers/requester/Recommended.js
  client/src/containers/requester/Requests.js
  client/src/routes.js
  docker-compose.yaml
Labels: NEXT UI

#598 Add build/ directory blocked by .gitignore
  client/src/semantic/tasks/build/assets.js
  client/src/semantic/tasks/build/css.js
  client/src/semantic/tasks/build/javascript.js
Labels: blocking

#599 Address batch deselect issue
  client/src/containers/approver/Individuals.js
Labels: bug

#601 Add initial notification labels
  client/src/components/layouts/Header.css
  client/src/components/layouts/Header.js
  client/src/components/layouts/TrackHeader.css
  client/src/components/nav/ApproverNav.css
  client/src/components/nav/ApproverNav.js
  client/src/components/nav/NavList.css
  client/src/components/nav/NavList.js
  client/src/components/nav/RequesterNav.js
  client/src/containers/app/App.css
  client/src/containers/app/App.js
  client/src/containers/app/AppHelper.js
  client/src/containers/requester/Recommended.css
  client/src/containers/requester/Requests.css
  client/src/redux/ApproverRedux.js
  client/src/routes.js
  client/src/semantic/semantic.css
  client/src/semantic/semantic.min.css
  client/src/semantic/themes/default/elements/label.overrides
  client/src/semantic/themes/default/elements/label.variables
  client/src/semantic/themes/default/elements/list.overrides
  client/src/semantic/themes/default/elements/list.variables
Labels: NEXT UI

#629 593 process existing outbound ldap records on startup
  bin/rbac-providers-ldap
  docker/rbac.providers.ldap.Dockerfile
  docker/tests.Dockerfile
  rbac/providers/azure/delta_outbound_sync.py
  rbac/providers/common/rethink_db.py
  rbac/providers/error/unrecoverable_error.py
  rbac/providers/ldap/delta_outbound_sync.py
  rbac/providers/ldap/ldap_inbound_sync.py
  rbac/providers/ldap/ldap_message_validator.py
  rbac/providers/ldap/ldap_outbound_service.py
  rbac/providers/ldap/ldap_payload_transformer.py
  rbac/providers/ldap/ldap_query_template.py
  rbac/providers/ldap/ldap_transforms.py
  rbac/providers/ldap/main.py
  rbac/providers/ldap/outbound_queue_listener.py
  rbac/providers/ldap/outbound_sync.py
  requirements.txt
  tests/unit/providers/ldap/ldap_message_validator_test.py
Labels: User Story
